#ifndef FUNCTIONS_REALIZATIONS_INCLUDE_CODEGEN_ALLLEXEMS_HPP
#define FUNCTIONS_REALIZATIONS_INCLUDE_CODEGEN_ALLLEXEMS_HPP

#define DELIM_LEXEM_DEF   GENERAL_LEXEM_DEF
#define KEYWORD_LEXEM_DEF   GENERAL_LEXEM_DEF
#define OPERATOR_LEXEM_DEF GENERAL_LEXEM_DEF

#include "delimsLexems.in"
#include "keywordsLexems.in"
#include "operatorsLexems.in"

#undef DELIM_LEXEM_DEF
#undef KEYWORD_LEXEM_DEF
#undef OPERATOR_LEXEM_DEF

#endif
